CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description  VARCHAR(512) NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id BIGINT,
    request_id   BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP without TIME ZONE DEFAULT now(),
    end_date   TIMESTAMP without TIME ZONE DEFAULT now(),
    item_id    BIGINT,
    booker_id  BIGINT,
    status     VARCHAR
);

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR(500),
    requester_id BIGINT,
    created TIMESTAMP without TIME ZONE DEFAULT now(),
    CONSTRAINT requests_users_id_fk
            REFERENCES users
);

CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(500),
    item_id   BIGINT,
    author_id BIGINT,
    created TIMESTAMP without TIME ZONE DEFAULT now(),
    CONSTRAINT comments_items_id_fk
        FOREIGN KEY (item_id) REFERENCES items
);
